/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gabrielgarcia.GUI;

import gabrielgarcia.Logica.Partido;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author damB
 */
public class Apuestas extends javax.swing.JDialog {
    GUI inicio;
    /**
     * Creates new form Apuestas
     */
    public Apuestas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicio = (GUI) parent;
        aniadirValores();
        
    }
    public void aniadirValores (){
        int Matriz [][] = inicio.getMatrix();
        List<Partido> partidos = inicio.getPartidos();
        int contador = 0;
        for (int i = 0; i < partidos.size(); i++) {
            String resultado = 
                    partidos.get(i).getGolesEquipo1() > partidos.get(i).getGolesEquipo2() ?
                    "Gana equipo 1" : 
                    partidos.get(i).getGolesEquipo1() < partidos.get(i).getGolesEquipo2() ?
                    "Gana equipo 2" : "Empate";
            String apuesta =
                    Matriz[i][0] == 1 ? "Gana equipo 1":
                    Matriz[i][2] == 1 ? "Gana equipo 2": "Empate";
            String resultadoApuesta = 
                    resultado.equals(apuesta) ? "CORRECTO" : "INCORRECTO";
            contador += resultadoApuesta.equals("CORRECTO") ? 1 :0;
            ((DefaultTableModel)jTableApuestas.getModel()).addRow(
                    new String[] {partidos.get(i).getEquipo1() + " - " + partidos.get(i).getEquipo2(),
                                  partidos.get(i).getGolesEquipo1()+"",
                                  partidos.get(i).getGolesEquipo2()+"",
                                  resultado,
                                  resultadoApuesta});
        }
        int apostado = Integer.parseInt(inicio.getjSpinnerApuesta().getValue().toString());
       
        String resultado7 = 
                partidos.get(6).getGolesEquipo1() > partidos.get(6).getGolesEquipo2() ?
                "Gana equipo 1" : 
                partidos.get(6).getGolesEquipo1() < partidos.get(6).getGolesEquipo2() ?
                    "Gana equipo 2" : "Empate";
        System.out.println(contador);
        String apuesta7 =
                    Matriz[6][0] == 1 ? "Gana equipo 1":
                    Matriz[6][2] == 1 ? "Gana equipo 2": "Empate";
        int premioFinal = premio(contador,resultado7,apostado,apuesta7);
        
        jLabelCantidadApostada.setText("Has ganado: " + premioFinal + "€");
    }
    public int premio(int contador,String resultado7,int apostado, String apuesta7){
        if (apuesta7.equals(resultado7) && contador == 7) {
            return apostado * 100;
        }
        if (apuesta7.equals(resultado7)) contador--;
        return contador == 5 ? apostado*10:
            contador == 6 ? apostado * 20:
                0;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableApuestas = new javax.swing.JTable();
        jLabelCantidadApostada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableApuestas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableApuestas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Partido", "Equipo 1", "Equipo 2", "Apuesta", "Acierto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableApuestas);

        jLabelCantidadApostada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCantidadApostada.setText("Has apostado:  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
            .addComponent(jLabelCantidadApostada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCantidadApostada)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Apuestas dialog = new Apuestas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCantidadApostada;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableApuestas;
    // End of variables declaration//GEN-END:variables
}
