/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gabrielgarcia.GUI;
import gabrielgarcia.Logica.Logica;
import gabrielgarcia.Logica.Partido;
import java.util.List;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;

/**
 *
 * @author damB
 */
public class GUI extends javax.swing.JFrame {
    int Matrix [][] = new int [7][3];
    JRadioButton casillas [][];
    Map<JRadioButton, String> MapCasillas = new HashMap<>();
    List<Partido> partidos = new ArrayList<>();
    String [] equipos;
    JLabel [] jlabels;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        inicializarVariables();
        aniadirEventos();
    }
    
    private void inicializarVariables(){
        equipos = new String [] {"Equipo 1","Equipo 2","Equipo 3","Equipo 4","Equipo 5","Equipo 6"};
        for (int[] Matrix1 : Matrix) {
            for (int j = 0; j < Matrix1.length; j++) {
                Matrix1[j] = 0;
                System.out.print(Matrix1[j]);
            }
            System.out.println("");
        }
        
        casillas = new JRadioButton[][] {{R00,R01,R02},{R10,R11,R12},
                                         {R20,R21,R22},{R30,R31,R32},
                                         {R40,R41,R42},{R50,R51,R52},
                                         {R60,R61,R62}};
        
        for (int i = 0; i < casillas.length; i++) {
            for (int j = 0; j < casillas[i].length; j++) {
                MapCasillas.put(casillas[i][j], i + "" + j);
            }
        }
        partidos = Logica.generarPartidos(equipos, 7);
        jlabels = new JLabel [] {jLabelPartido1,jLabelPartido2,jLabelPartido3,
                                jLabelPartido4,jLabelPartido5,jLabelPartido6,
                                jLabelPartido7};
        for (int i = 0; i < jlabels.length; i++) {
            jlabels[i].setText(partidos.get(i).getEquipo1() + " - "+partidos.get(i).getEquipo2() );
        }
    }
    private void aniadirEventos(){
        for (Map.Entry<JRadioButton, String> boton : MapCasillas.entrySet()) {
            boton.getKey().addActionListener((ActionEvent e) -> {
                registarApuesta(e);
            });
        }
    }

    public List<Partido> getPartidos() {
        return partidos;
    }
    
    public void registarApuesta(ActionEvent e){
        JRadioButton radioButton;
        String nombre = "";
        for (Map.Entry<JRadioButton, String> casilla : MapCasillas.entrySet()) {
            if (e.getSource() == casilla.getKey()) {
                radioButton = casilla.getKey();
                nombre = casilla.getValue();
            }
        }
        int fila =  Character.getNumericValue((char)nombre.charAt(0));
        int columna = Character.getNumericValue((char)nombre.charAt(1));
        Matrix[fila][0] = 0;
        Matrix[fila][1] = 0;
        Matrix[fila][2] = 0;
        Matrix[fila][columna] = 1;
        System.out.println(Matrix[fila][0] + " " + Matrix[fila][1] +
                " " + Matrix[fila][2]);     
        comprobacionRegistrar();
        
    }

    public JSpinner getjSpinnerApuesta() {
        return jSpinnerApuesta;
    }

    public int[][] getMatrix() {
        return Matrix;
    }
    public void comprobacionRegistrar(){
        int comprobador = 0;
        for (int i = 0; i < Matrix.length; i++) {
            comprobador += Matrix[i][0] + Matrix[i][1] + Matrix[i][2];
        }
        if (comprobador == 7) {
            ComprobarButton.setEnabled(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupEquipo1 = new javax.swing.ButtonGroup();
        buttonGroupEquipo2 = new javax.swing.ButtonGroup();
        buttonGroupEquipo3 = new javax.swing.ButtonGroup();
        buttonGroupEquipo4 = new javax.swing.ButtonGroup();
        buttonGroupEquipo5 = new javax.swing.ButtonGroup();
        buttonGroupEquipo6 = new javax.swing.ButtonGroup();
        buttonGroupEquipo7 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelPartido1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        R00 = new javax.swing.JRadioButton();
        R01 = new javax.swing.JRadioButton();
        R02 = new javax.swing.JRadioButton();
        jLabelPartido2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        R10 = new javax.swing.JRadioButton();
        R11 = new javax.swing.JRadioButton();
        R12 = new javax.swing.JRadioButton();
        jLabelPartido3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        R20 = new javax.swing.JRadioButton();
        R21 = new javax.swing.JRadioButton();
        R22 = new javax.swing.JRadioButton();
        jLabelPartido4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        R30 = new javax.swing.JRadioButton();
        R31 = new javax.swing.JRadioButton();
        R32 = new javax.swing.JRadioButton();
        jLabelPartido5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        R40 = new javax.swing.JRadioButton();
        R41 = new javax.swing.JRadioButton();
        R42 = new javax.swing.JRadioButton();
        jLabelPartido6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        R50 = new javax.swing.JRadioButton();
        R51 = new javax.swing.JRadioButton();
        R52 = new javax.swing.JRadioButton();
        jLabelPartido7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        R60 = new javax.swing.JRadioButton();
        R61 = new javax.swing.JRadioButton();
        R62 = new javax.swing.JRadioButton();
        ComprobarButton = new javax.swing.JButton();
        jSpinnerApuesta = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(7, 2, 1, 1));

        jLabelPartido1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPartido1.setText("Equipo 1");
        jPanel1.add(jLabelPartido1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 3));

        buttonGroupEquipo1.add(R00);
        jPanel2.add(R00);

        buttonGroupEquipo1.add(R01);
        jPanel2.add(R01);

        buttonGroupEquipo1.add(R02);
        R02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R02ActionPerformed(evt);
            }
        });
        jPanel2.add(R02);

        jPanel1.add(jPanel2);

        jLabelPartido2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPartido2.setText("Equipo 2");
        jPanel1.add(jLabelPartido2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 3));

        buttonGroupEquipo2.add(R10);
        jPanel3.add(R10);

        buttonGroupEquipo2.add(R11);
        jPanel3.add(R11);

        buttonGroupEquipo2.add(R12);
        jPanel3.add(R12);

        jPanel1.add(jPanel3);

        jLabelPartido3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPartido3.setText("Equipo 3");
        jPanel1.add(jLabelPartido3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 3));

        buttonGroupEquipo3.add(R20);
        jPanel4.add(R20);

        buttonGroupEquipo3.add(R21);
        jPanel4.add(R21);

        buttonGroupEquipo3.add(R22);
        jPanel4.add(R22);

        jPanel1.add(jPanel4);

        jLabelPartido4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPartido4.setText("Equipo 4");
        jPanel1.add(jLabelPartido4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 3));

        buttonGroupEquipo4.add(R30);
        jPanel5.add(R30);

        buttonGroupEquipo4.add(R31);
        jPanel5.add(R31);

        buttonGroupEquipo4.add(R32);
        jPanel5.add(R32);

        jPanel1.add(jPanel5);

        jLabelPartido5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPartido5.setText("Equipo 5");
        jPanel1.add(jLabelPartido5);

        jPanel6.setLayout(new java.awt.GridLayout(1, 3));

        buttonGroupEquipo5.add(R40);
        jPanel6.add(R40);

        buttonGroupEquipo5.add(R41);
        jPanel6.add(R41);

        buttonGroupEquipo5.add(R42);
        jPanel6.add(R42);

        jPanel1.add(jPanel6);

        jLabelPartido6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPartido6.setText("Equipo 6");
        jPanel1.add(jLabelPartido6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 3));

        buttonGroupEquipo6.add(R50);
        jPanel7.add(R50);

        buttonGroupEquipo6.add(R51);
        jPanel7.add(R51);

        buttonGroupEquipo6.add(R52);
        jPanel7.add(R52);

        jPanel1.add(jPanel7);

        jLabelPartido7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPartido7.setText("Equipo 7");
        jPanel1.add(jLabelPartido7);

        jPanel8.setLayout(new java.awt.GridLayout(1, 3));

        buttonGroupEquipo7.add(R60);
        jPanel8.add(R60);

        buttonGroupEquipo7.add(R61);
        jPanel8.add(R61);

        buttonGroupEquipo7.add(R62);
        jPanel8.add(R62);

        jPanel1.add(jPanel8);

        ComprobarButton.setText("Registrar apuesta");
        ComprobarButton.setEnabled(false);
        ComprobarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprobarButtonActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("APUESTA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(ComprobarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinnerApuesta)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComprobarButton)
                    .addComponent(jSpinnerApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void R02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R02ActionPerformed

    private void ComprobarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprobarButtonActionPerformed
        if (Double.parseDouble(jSpinnerApuesta.getValue().toString()) <= 0) {
            JOptionPane.showMessageDialog(rootPane, "Apuesta minima 1 €");
        } else{
            Apuestas a = new Apuestas(this,true);
            a.setVisible(true);
        }
    }//GEN-LAST:event_ComprobarButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ComprobarButton;
    private javax.swing.JRadioButton R00;
    private javax.swing.JRadioButton R01;
    private javax.swing.JRadioButton R02;
    private javax.swing.JRadioButton R10;
    private javax.swing.JRadioButton R11;
    private javax.swing.JRadioButton R12;
    private javax.swing.JRadioButton R20;
    private javax.swing.JRadioButton R21;
    private javax.swing.JRadioButton R22;
    private javax.swing.JRadioButton R30;
    private javax.swing.JRadioButton R31;
    private javax.swing.JRadioButton R32;
    private javax.swing.JRadioButton R40;
    private javax.swing.JRadioButton R41;
    private javax.swing.JRadioButton R42;
    private javax.swing.JRadioButton R50;
    private javax.swing.JRadioButton R51;
    private javax.swing.JRadioButton R52;
    private javax.swing.JRadioButton R60;
    private javax.swing.JRadioButton R61;
    private javax.swing.JRadioButton R62;
    private javax.swing.ButtonGroup buttonGroupEquipo1;
    private javax.swing.ButtonGroup buttonGroupEquipo2;
    private javax.swing.ButtonGroup buttonGroupEquipo3;
    private javax.swing.ButtonGroup buttonGroupEquipo4;
    private javax.swing.ButtonGroup buttonGroupEquipo5;
    private javax.swing.ButtonGroup buttonGroupEquipo6;
    private javax.swing.ButtonGroup buttonGroupEquipo7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelPartido1;
    private javax.swing.JLabel jLabelPartido2;
    private javax.swing.JLabel jLabelPartido3;
    private javax.swing.JLabel jLabelPartido4;
    private javax.swing.JLabel jLabelPartido5;
    private javax.swing.JLabel jLabelPartido6;
    private javax.swing.JLabel jLabelPartido7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSpinner jSpinnerApuesta;
    // End of variables declaration//GEN-END:variables
}
